### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by AumBhatt** [AumBhatt/aura-zmote#1]
- [ ] #5
   - [ ] Discovery Request
   - [ ] Target Wi-Fi Connection Request
   - [x] Send IR Command Request
   - [x] Request Error Handling
- [x] #6
   - [x] `get_IRL`
   - [x] `stop_IRL`
      - [x] C++ Client
      - [x]  Express.js Server
- [x] HTTP Response
   - [x]
